![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [10]:
# Crear un array que vaya del 0 al 9:
my_array = np.array(range(10))
print(my_array)
# Imprimir por pantalla los impares al reves:
print(my_array[my_array % 2 != 0][::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [11]:
# Imprimir por pantalla [8,7] del array:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [ ]:
# Imprimir por pantalla la secuencia [2 1 0]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [15]:
# Crear una matriz 4x5 con una secuencia del 1 al 20:
my_matrix = np.array(range(1, 21)).reshape(4, 5)
print(my_matrix)
# Invertir la matriz tanto por filas como por columnas:
print(my_matrix[::-1, ::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [20]:
# Partiendo de my_matrix, crear el array:
array_1 = my_matrix[:2, :2]
array_1

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
# Patiendo de my_matrix, crear el array:
array_2 = my_matrix[::2, ::2]
array_2

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [29]:
# Partiendo de my_matrix, 
array_3 = my_matrix[:3,::-1]
array_3

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [34]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
# Filtrar el array para quedarnos solo con los "Loro", con máscara:
array_8 = x[x == "Loro"]
print(array_8)
# Filtrar el array para quedarnos solo con los "Loro", con np.where:
array_8b = x[np.where(x == "Loro")]
print(array_8b)

['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [36]:
# Crea una secuencia de 20 elementos y transformarla en un array compuesto por 2 matrices de 5x2:
array_9 = np.array(range(20)).reshape(2, 5, 2)
print(array_9)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [38]:
# Crea un array de 10 0s y ver cuanto ocupa en memoria:
array_10 = np.zeros(10)
print(array_10.nbytes)
# El array ocupa 80 bytes, ya que cada elemento es un float64 que ocupa 8 bytes.
# Sustituir el 4o elemento por 1:
array_10[3] = 1
print(array_10)

80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [39]:
# Crea un vector que vaya del 10 al 49 y despues invertir su orden:
array_11_a = np.array(range(10, 50))
array_11_b = array_11_a[::-1]
print(array_11_b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [44]:
def valores_no_cero(vector):
    return vector[np.nonzero(vector)]

# Prueba:
v = np.array([1, 2, 0, 0, 4, 0])
print(valores_no_cero(v))

[1 2 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [45]:
matriz_13 = np.random.random((10, 10))
print("Mínimo:", matriz_13.min())
print("Máximo:", matriz_13.max())

Mínimo: 0.016651111619539583
Máximo: 0.9959477104658702


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [46]:
vector_14 = np.random.random(30)
print("Media:", vector_14.mean())

Media: 0.5796191289540106


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [47]:
n = 6  # el tamaño que quieras
array_15 = np.zeros((n, n))
array_15[0, :] = 1    # fila superior
array_15[-1, :] = 1   # fila inferior
array_15[:, 0] = 1    # columna izquierda
array_15[:, -1] = 1   # columna derecha
print(array_15)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [48]:
array_16 = np.zeros((8, 8), dtype=int)
array_16[::2, 1::2] = 1   # filas pares, columnas impares
array_16[1::2, ::2] = 1   # filas impares, columnas pares
print(array_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [49]:
array_17 = np.tile([[0, 1], [1, 0]], (4, 4))
print(array_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [50]:
matriz_18 = np.random.random((5, 5))
normalizada = (matriz_18 - np.mean(matriz_18)) / np.std(matriz_18)
print(normalizada)

[[-1.14353843 -1.18586554 -1.17099229  1.05236139  1.34523128]
 [ 0.1039461  -0.22512441 -0.89005191  0.40097064  1.70967051]
 [ 1.95966155 -0.64873793 -0.28732841 -1.04079919  0.26090588]
 [ 1.08492745 -0.71347065  0.44769812  1.5331249  -1.00749071]
 [-0.36767897 -0.8654531  -1.28144017  0.0434563   0.88601759]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
# 1. Secuencia del 0 al 10
seq = np.arange(0, 11)

# 2. Sustituir por -1 los valores entre 3 y 8
array_19b = np.where((seq > 3) & (seq < 8), -1, seq)
print(array_19b)

# 3. Negar elementos entre 3 y 8
array_19c = np.where((seq > 3) & (seq < 8), -seq, seq)
print(array_19c)